### ISSUE TITLE
With multiple fields on the same object, something seems odd

### ISSUE THREAD

**Issue by Firesphere** [kinglozzer/silverstripe-multiselectfield#1]
![multi-image](https://cloud.githubusercontent.com/assets/680570/7783830/79126d2e-0150-11e5-8f87-b107adb5fb6d.PNG)

**Comment by kinglozzer** [comment]
@Firesphere I can’t recreate this, can you provide steps and/or a simplified code example?

![screen shot 2015-05-23 at 18 56 13](https://cloud.githubusercontent.com/assets/1655548/7785217/74658a72-017d-11e5-9f2a-80b5a32a10e3.png)

**Comment by Firesphere** [comment]
Maybe related to some other modules I use?
Best guess is Better Buttons as the cause of this.

**Comment by kinglozzer** [comment]
Hmm, I still can’t recreate it with betterbuttons installed. Let me know if you discover the cause and I’ll try to fix it!

**Comment by Firesphere** [comment]
I'll go test some things if I can find a way to reproduce this :)

**Comment by Firesphere** [comment]
I think I know what's wrong. I had the fields loaded via a dataextension with updateCMSFields();

Using an updated version with a different way of building the cmsfields, and using getCMSFields in the object, all is well.

So, nothing important, maybe something to look at another day.
