### ISSUE TITLE
SilverStripe 4

### ISSUE THREAD

**Issue by jfullerton** [kinglozzer/silverstripe-multiselectfield#11]
Just curious if there are any plans at all to maintain this going forward into SilverStripe v4?

**Comment by kinglozzer** [comment]
I plan to have _something_ for SilverStripe 4. I did do a cursory search a while back for a more modern library than jQuery UI’s multiselect component, a React component ideally, but didn’t find much at the time

**Comment by kinglozzer** [comment]
This is functional in SS4 now. It still uses jQuery UI, but tbh I think this module needs starting from scratch instead of updating.
