### ISSUE TITLE
MultiSelectField.js missing _super calls

### ISSUE THREAD

**Issue by ElGabbu** [kinglozzer/silverstripe-multiselectfield#13]
Hi

We are using the module and want to extend using entwine some logic to the initialise event. However we were unable to since it would see the function are missing the this._super(); call. 

Would appreciate if you could give us some feedback what you think. 

Thanks

**Comment by kinglozzer** [comment]
Untested, but you should be able to do that by specifying a higher-specificity CSS selector... something like:

```js
(function($) {
    $.entwine(function($) {
        $('body select.multiselectfield').entwine({
            initialise: function() {
                console.log('test');
                this._super();
            }
        });
    });
})(jQuery);
```

**Comment by ElGabbu** [comment]
Indeed yes, so the order of execution is determined by the specificity of the selector. Thanks

**Comment by ElGabbu** [comment]
@kinglozzer another issue we seem to have noticed is the redraw function triggers and error we managed to work around by destroying and re-intializing. 

```
redraw: function() {
        this.data('initialised',false);
	this.multiselect('destroy');
	this.initialise();
},
```
