### ISSUE TITLE
Overloading title

### ISSUE THREAD

**Issue by jackkemmish** [kinglozzer/silverstripe-multiselectfield#20]
Hi there,

Is there a nice way to overload the title for the items?

For example, we have a few pages with the same names, so would like ot include the parent title e.g. `Product (Parent one)`.

Thanks,
Jack

**Comment by lozcalver** [comment]
There’s a constructor argument for the title field: https://github.com/kinglozzer/silverstripe-multiselectfield/blob/master/src/Forms/MultiSelectField.php#L59. You could set that to `MyCustomTItle` and add a `getMyCustomTitle()` method to your model
