### ISSUE TITLE
Enhancement: Querying database if amount of records is high

### ISSUE THREAD

**Issue by Firesphere** [kinglozzer/silverstripe-multiselectfield#3]
One of my many_many relations is about 50k records. This is quite hard for the browser to handle. Maybe it is possible to limit to 100 items, and after that, query the database onKeyUp?

**Comment by Firesphere** [comment]
Anything on this?

**Comment by kinglozzer** [comment]
Hey @Firesphere. I’m afraid not, but your suggestion sounds reasonable - perhaps via a new method like `->setLazyLoad(true)`? Exactly how that would integrate with the multiselect jQuery UI plugin I’m not sure, though... PR would be welcome if you can get it working :)

**Comment by kinglozzer** [comment]
I don’t think this enhancement is going to happen - the module needs rebuilding from scratch anyway (PHP logic is horrible, client-side is all still jQuery UI 🤢)
